project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  scripts: scripts
  tests: tests

networks:
  development:
    host: http://127.0.0.1:7545 
    chainid: 5777 
    gas_price: 10
    uniswap_v2_factory_address: "0x6b1E8E2A121dBa4cb831DfFbdC39ce6b02Fa894e"
    live:
      gas_limit: 10000
      gas_buffer: 1.1
      gas_price: 5
      max_fee: null
      priority_fee: null
      reverting_tx_gas_limit: false
      default_contract_owner: false

compiler:
  solc:
    version: "0.8.0"
    remappings: -'../node_modules/@uniswap/v2-core/contracts/interfaces/IUniswapV2Factory.sol'

console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true
  editing_mode: emacs

reports:
  exclude_paths: null
  exclude_contracts: null
  only_include_project: true

hypothesis:
  deadline: null
  max_examples: 50
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

autofetch_sources: false
dependencies: null
dev_deployment_artifacts: false
